queue_rules:
  - name: auto merge
    queue_conditions:
      - author = meny2333
      - -draft
      - -conflict
merge_protections_settings:
  auto_merge_conditions:
    - -conflict
    - -draft
    - base = main
    - author = meny2333
